modded class BBP_Blueprint
{
  // crude attempt to remove step ladder blueprint
	override void RegisterRecipies(){
		// super.RegisterRecipies();
		AddNewRecipe(new BBPRecipeBase("Wall Kit", "BBP_Wall_Kit", new BBPRecipePreviewItem("BBP_Bwall", {"frame","t1_door","t1_wall_planks"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Door Kit", "BBP_Door_Kit", new BBPRecipePreviewItem("BBP_BDoor", {"frame","t1_door","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3) }, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Floor Kit", "BBP_Floor_Kit", new BBPRecipePreviewItem("BBP_Bfloor", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Roof Kit", "BBP_Roof_Kit", new BBPRecipePreviewItem("BBP_Broof", {"frame","t1_door","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Gate Kit", "BBP_Gate_Kit", new BBPRecipePreviewItem("BBP_RGate", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Garage Door Kit", "BBP_SGate_Kit", new BBPRecipePreviewItem("BBP_SGate", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Ramp Kit", "BBP_Ramp_Kit", new BBPRecipePreviewItem("BBP_Bramp", {"frame"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Stair Kit", "BBP_Stair_Kit", new BBPRecipePreviewItem("BBP_Bstair", {"frame"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Window Kit", "BBP_Window_Kit", new BBPRecipePreviewItem("BBP_BWindow", {"frame","t1_wall_planks"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Half Wall Kit", "BBP_Half_Wall_Kit", new BBPRecipePreviewItem("BBP_Half_Bwall", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Pillar Kit", "BBP_Pillar_Kit", new BBPRecipePreviewItem("BBP_Bpillar", {"frame"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Hanger Roof Kit", "BBP_Hanger_Roof_Kit", new BBPRecipePreviewItem("BBP_LHanger_Roof", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Triangle Foundation Kit", "BBP_Triangle_Foundation_Kit", new BBPRecipePreviewItem("BBP_Triangle_Foundation", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Foundation Kit", "BBP_Foundation_Kit", new BBPRecipePreviewItem("BBP_BFoundation", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Roof Hatch Kit", "BBP_Roof_Hatch_Kit", new BBPRecipePreviewItem("BBP_Roof_Hatch", {"frame","t1_wall_logs_horizontal", "stair"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Floor Hatch Kit", "BBP_Floor_Hatch_Kit", new BBPRecipePreviewItem("BBP_Floor_Hatch", {"frame","t1_wall_logs_horizontal", "stair"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));		
		AddNewRecipe(new BBPRecipeBase("Slope Roof Kit", "BBP_Slope_Roof_Kit", new BBPRecipePreviewItem("BBP_Slope_Roof", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Slope Wall Kit", "BBP_Slope_Wall_Kit", new BBPRecipePreviewItem("BBP_Left_Slope_Wall", {"frame","t1_wall_planks"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Triangle Floor Kit", "BBP_Triangle_Floor_Kit", new BBPRecipePreviewItem("BBP_Triangle_Bfloor", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Triangle Roof Kit", "BBP_Triangle_Roof_Kit", new BBPRecipePreviewItem("BBP_Triangle_Broof", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Barbwire Barrier Kit", "BBP_Barbwire_Fence_Kit", new BBPRecipePreviewItem("BBP_Barbwire_Fence", {"frame","t1_wall_logs_horizontal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Chain Link Fence Kit", "BBP_Mesh_Fence_Kit", new BBPRecipePreviewItem("BBP_Mesh_Fence", {"frame","t2_metal","t2_metal_2"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Chain Link Gate Kit", "BBP_Mesh_Gate_Kit", new BBPRecipePreviewItem("BBP_Mesh_Gate", {"frame","t2_metal","t2_door","t2_metal_2"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Metal Floor Mesh Kit", "BBP_Floor_Mesh_Kit", new BBPRecipePreviewItem("BBP_Floor_Mesh", {"frame","t2_metal"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Metal Stair Kit", "BBP_Metal_Stair_Kit", new BBPRecipePreviewItem("BBP_Metal_Stair", {"frame","railing_1","railing_2"}, "30 -15 190"), { new BBPRecipeItem("Nail", 15), new BBPRecipeItem("WoodenPlank", 3)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		// AddNewRecipe(new BBPRecipeBase("Step Ladder", "BBP_Step_Ladder_Kit", new BBPRecipePreviewItem("BBP_Step_Ladder_Kit", {}, "30 -15 190"), { new BBPRecipeItem("Nail", 20), new BBPRecipeItem("WoodenPlank", 10)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
	}
}
