class CfgPatches
{
	class Survivalists_Mods_Characters__Pants
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Characters",
      "DZ_Characters_Pants"
		};
	};
};
class CfgVehicles
{

  class ParamedicPants_ColorBase;

	class Medic_P_black: ParamedicPants_ColorBase  // Medic_P_black
	{
		scope=2;
		displayName="Black Medic Pants";
		itemSize[]={3,3};
		itemsCargoSize[]={6,6};
		weight=200;
		absorbency=0.0099999998;
		heatIsolation=0.60000002;
		quickBarBonus=2;
		hiddenSelectionsTextures[]=
		{
			"BP1\camo\characters_pants\data\Paramedic_Pants_Black.paa",
			"BP1\camo\characters_pants\data\Paramedic_Pants_Black.paa",
			"BP1\camo\characters_pants\data\Paramedic_Pants_Black.paa"
		};
	};
	class BP1_Beliypants: HunterPants_ColorBase  // BP1_Beliypants
	{
		scope=2;
		itemSize[]={4,3};
		itemsCargoSize[]={6,6};
		weight=230;
		ragQuantity=3;
		quickBarBonus=4;
		hiddenSelectionsTextures[]=
		{
			"BP1\camo\characters_pants\data\Beliypants.paa",
			"BP1\camo\characters_pants\data\Beliypants.paa",
			"BP1\camo\characters_pants\data\Beliypants.paa"
		};
	};
	class BP_wkpants: PolicePantsOrel  // BP_wkpants
	{
		scope=2;
		heatIsolation=0.89999998;
		absorbency=0.02;
		visibilityModifier=0.89999998;
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\wkpants_co.paa",
			"BP2\camo\pants\data\wkpants_co.paa",
			"BP2\camo\pants\data\wkpants_co.paa"
		};
	};
	class BP_Janek_Pants2: HunterPants_ColorBase  // BP_Janek_Pants2
	{
		scope=2;
		absorbency=0.02;
		visibilityModifier=0.89999998;
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\janekpants2.paa",
			"BP2\camo\pants\data\janekpants2.paa",
			"BP2\camo\pants\data\janekpants2.paa"
		};
	};
	class BP_Janek_Pants: CargoPants_ColorBase  // BP_Janek_Pants
	{
		scope=2;
		absorbency=0.02;
		visibilityModifier=0.89999998;
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\Janek_pants.paa",
			"BP2\camo\pants\data\Janek_pants.paa",
			"BP2\camo\pants\data\Janek_pants.paa"
		};
	};
	class BP2_TrackSuitPants_boj: TrackSuitPants_ColorBase  // BP2_TrackSuitPants_boj
	{
		scope=2;
		itemSize[]={3,3};
		itemsCargoSize[]={6,5};
		weight=490;
		ragQuantity=3;
		absorbency=0.30000001;
		heatIsolation=0.85000002;
		quickBarBonus=2;
		hiddenSelections[]=
		{
			"camoGround",
			"camoMale",
			"camoFemale"
		};
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\tracksuit_pants_boj.paa",
			"BP2\camo\pants\data\tracksuit_pants_boj.paa",
			"BP2\camo\pants\data\tracksuit_pants_boj.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"BP2\camo\pants\data\tracksuit_pants_boj.rvmat",
			"BP2\camo\pants\data\tracksuit_pants_boj.rvmat",
			"BP2\camo\pants\data\tracksuit_pants_boj.rvmat"
		};
	};
	class BP2_Beliyprison: PrisonUniformPants  // BP2_Beliyprison
	{
		scope=2;
		itemSize[]={3,2};
		itemsCargoSize[]={6,5};
		weight=310;
		absorbency=0.60000002;
		heatIsolation=0.40000001;
		quickBarBonus=3;
		hiddenSelections[]=
		{
			"camoGround",
			"camoMale",
			"camoFemale"
		};
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\beliypris.paa",
			"BP2\camo\pants\data\beliypris.paa",
			"BP2\camo\pants\data\beliypris.paa"
		};
	};
	class BP2_PrisonBlue: PrisonUniformPants  // BP2_PrisonBlue
	{
		scope=2;
		itemSize[]={3,2};
		itemsCargoSize[]={6,5};
		weight=310;
		ragQuantity=3;
		absorbency=0;
		heatIsolation=0.89999998;
		quickBarBonus=3;
		hiddenSelections[]=
		{
			"camoGround",
			"camoMale",
			"camoFemale"
		};
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\prison_pants_blue_co.paa",
			"BP2\camo\pants\data\prison_pants_blue_co.paa",
			"BP2\camo\pants\data\prison_pants_blue_co.paa"
		};
	};
	class BP2_Rainpants: CargoPants_ColorBase  // BP2_Rainpants
	{
		scope=2;
		itemsCargoSize[]={6,4};
		weight=530;
		absorbency=0.30000001;
		heatIsolation=0.80000001;
		quickBarBonus=3;
		hiddenSelections[]=
		{
			"camoGround",
			"camoMale",
			"camoFemale"
		};
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\rainpants.paa",
			"BP2\camo\pants\data\rainpants.paa",
			"BP2\camo\pants\data\rainpants.paa"
		};
	};
	class BP2_Banditpants: CargoPants_ColorBase  // BP2_Banditpants
	{
		scope=2;
		displayName="$STR_CfgVehicles_CargoPants_ColorBase0";
		descriptionShort="";
		absorbency=0.60000002;
		heatIsolation=0.69999999;
		quickBarBonus=2;
		hiddenSelections[]=
		{
			"camoGround",
			"camoMale",
			"camoFemale"
		};
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\cargopants_grey_co2_2.paa",
			"BP2\camo\pants\data\cargopants_grey_co2_2.paa",
			"BP2\camo\pants\data\cargopants_grey_co2_2.paa"
		};
	};
	class BP2_Banditpants1: CargoPants_ColorBase  // BP2_Banditpants1
	{
		scope=2;
		displayName="$STR_CfgVehicles_CargoPants_ColorBase0";
		descriptionShort="";
		absorbency=0.60000002;
		heatIsolation=0.69999999;
		quickBarBonus=2;
		hiddenSelections[]=
		{
			"camoGround",
			"camoMale",
			"camoFemale"
		};
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\cargopants_grey_co3.paa",
			"BP2\camo\pants\data\cargopants_grey_co3.paa",
			"BP2\camo\pants\data\cargopants_grey_co3.paa"
		};
	};
	class BP2_Banditpants2: CargoPants_ColorBase  // BP2_Banditpants2
	{
		scope=2;
		displayName="$STR_CfgVehicles_CargoPants_ColorBase0";
		descriptionShort="";
		absorbency=0.60000002;
		heatIsolation=0.69999999;
		quickBarBonus=2;
		hiddenSelections[]=
		{
			"camoGround",
			"camoMale",
			"camoFemale"
		};
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\cargopants_grey_co4.paa",
			"BP2\camo\pants\data\cargopants_grey_co4.paa",
			"BP2\camo\pants\data\cargopants_grey_co4.paa"
		};
	};
	class BP2_Banditpants3: CargoPants_ColorBase  // BP2_Banditpants3
	{
		scope=2;
		displayName="$STR_CfgVehicles_CargoPants_ColorBase0";
		descriptionShort="";
		absorbency=0.60000002;
		heatIsolation=0.69999999;
		quickBarBonus=2;
		hiddenSelections[]=
		{
			"camoGround",
			"camoMale",
			"camoFemale"
		};
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\cargopants_grey_co5.paa",
			"BP2\camo\pants\data\cargopants_grey_co5.paa",
			"BP2\camo\pants\data\cargopants_grey_co5.paa"
		};
	};
	class BP2_Dencargo: CargoPants_ColorBase  // BP2_Dencargo
	{
		scope=2;
		displayName="$STR_CfgVehicles_CargoPants_ColorBase0";
		descriptionShort="$STR_CfgVehicles_CargoPants_ColorBase1";
		model="\DZ\characters\pants\cargoPants_g.p3d";
		itemSize[]={4,3};
		itemsCargoSize[]={6,4};
		weight=530;
		ragQuantity=3;
		absorbency=0.02;
		heatIsolation=0.80000001;
		quickBarBonus=3;
		hiddenSelections[]=
		{
			"camoGround",
			"camoMale",
			"camoFemale"
		};
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\dencarg.paa",
			"BP2\camo\pants\data\dencarg.paa",
			"BP2\camo\pants\data\dencarg.paa"
		};
	};
	class BP2_NBCP_Orange: NBCPantsBase  // BP2_NBCP_Orange
	{
		scope=2;
		itemSize[]={3,4};
		itemsCargoSize[]={2,2};
		weight=2000;
		absorbency=0.1;
		heatIsolation=0.69999999;
		repairableWithKits[]={6};
		hiddenSelections[]=
		{
			"camoGround",
			"camoMale",
			"camoFemale"
		};
		hiddenSelectionsTextures[]=
		{
			"BP2\camo\pants\data\nbc_pants_orange_co.paa",
			"BP2\camo\pants\data\nbc_pants_orange_co.paa",
			"BP2\camo\pants\data\nbc_pants_orange_co.paa"
		};
		class ClothingTypes
		{
			male="\DZ\characters\pants\NBC_Pants_m.p3d";
			female="\DZ\characters\pants\NBC_Pants_f.p3d";
		};
	};
};