class CfgPatches
{
	class Survivalists_Mods_Gear_Books
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
            "Dressupbox_Items"
		};
	};
};
class CfgVehicles
{
  class Inventory_Base;

  //----------------------------------------- MODDED OVERRIDE
  class DUB_Newspaper_Base: Inventory_Base
	{
    inventorySlot[]+=
		{
			"Book_slot",
			"OpenBook",
			"Book1",
			"Book2",
			"Book3",
			"Book4",
			"Book5",
			"Book6",
			"Book7",
			"Book8",
			"Book9",
			"Book10",
			"Book11",
			"Book12",
			"Book13",
			"Book14",
			"Book15",
			"Book16",
			"Book17",
			"Book18",
			"Book19",
			"Book20",
			"Book21",
			"Book22",
			"Book23",
			"Book24",
			"Book25",
			"Book26",
			"Book27",
			"Book28",
			"Book29",
			"Book30",
			"Book31",
			"Book32",
			"Book33",
			"Book34",
			"Book35",
			"Book36",
			"Book37",
			"Book38",
			"Book39",
			"Book40",
			"Book41",
			"Book42",
			"Book43",
			"Book44",
			"Book45",
			"Book46",
			"Book47",
			"Book48",
			"Book49",
			"Book50",
      "SRP_Book1",
			"SRP_Book2",
			"SRP_Book3",
			"SRP_Book4",
			"SRP_Book5",
			"SRP_Book6",
			"SRP_Book7",
			"SRP_Book8",
			"SRP_Book9",
			"SRP_Book10",
			"SRP_Book11",
			"SRP_Book12",
			"SRP_Book13",
			"SRP_Book14",
			"SRP_Book15",
			"SRP_Book16",
			"SRP_Book17",
			"SRP_Book18",
			"SRP_Book19",
			"SRP_Book20",
		};
  };
};