class CfgPatches
{
	class Survivalists_RPWeapons_Rifles_ESP_G36C
	{
		units[]=
		{
			"ESP_G36C"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Weapons_Firearms"
		};
	};
};
class Mode_Safe;
class Mode_SemiAuto;
class Mode_FullAuto;
class OpticsInfoRifle;
class CfgWeapons
{
	class FAL_Base;
	class ESP_G36C: FAL_Base
	{
		scope=2;
		displayName="ESP-G36";
		descriptionShort="ESP-G36 is a gas-operated automatic rifle developed by Espen Industries. Chambered in 5.56x45, compatible with STANAG & CMag magazines.";
		model="Survivalists_RPWeapons\rifles\ESP_G36C\ESP_G36C.p3d";
		hasRailFunctionality=0;
		attachments[]=
		{
			"weaponOptics",
			"weaponMuzzleM4",
			"weaponWrap",
			"RISLeft",
			"RISRight",
			"RISBottom"
		};
		ironsightsExcludingOptics[]=
		{
			"M4_CarryHandleOptic",
			"BUISOptic",
			"M68Optic",
			"M4_T3NRDSOptic",
			"ReflexOptic",
			"ACOGOptic"
		};
		itemSize[]={7,3};
		chamberableFrom[]=
		{
			"Ammo_556x45",
			"Ammo_556x45Tracer"
		};
		magazines[]=
		{
			"Mag_STANAG_30Rnd",
			"Mag_STANAGCoupled_30Rnd",
			"Mag_STANAG_60Rnd",
			"Mag_CMAG_10Rnd",
			"Mag_CMAG_20Rnd",
			"Mag_CMAG_30Rnd",
			"Mag_CMAG_40Rnd",
			"Mag_CMAG_10Rnd_Green",
			"Mag_CMAG_20Rnd_Green",
			"Mag_CMAG_30Rnd_Green",
			"Mag_CMAG_40Rnd_Green",
			"Mag_CMAG_10Rnd_Black",
			"Mag_CMAG_20Rnd_Black",
			"Mag_CMAG_30Rnd_Black",
			"Mag_CMAG_40Rnd_Black"
		};
		magazineSwitchTime=0.5;
		ejectType=1;
		recoilModifier[]={1,1,1};
		swayModifier[]={2,2,1.1};
		spawnDamageRange[]={0,0.60000002};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints=300;
					healthLevels[]=
					{						
						{1,{"Survivalists_RPWeapons\rifles\ESP_G36C\data\ESP_G36C.rvmat","Survivalists_RPWeapons\rifles\ESP_G36C\data\ESP_G36C_Body.rvmat"}},						
						{0.69999999,{"Survivalists_RPWeapons\rifles\ESP_G36C\data\ESP_G36C.rvmat","Survivalists_RPWeapons\rifles\ESP_G36C\data\ESP_G36C_Body.rvmat"}},						
						{0.5,{"Survivalists_RPWeapons\rifles\ESP_G36C\data\ESP_G36C.rvmat","Survivalists_RPWeapons\rifles\ESP_G36C\data\ESP_G36C_Body.rvmat"}},						
						{0.30000001,{"Survivalists_RPWeapons\rifles\ESP_G36C\data\ESP_G36C.rvmat","Survivalists_RPWeapons\rifles\ESP_G36C\data\ESP_G36C_Body.rvmat"}},						
						{0,{"Survivalists_RPWeapons\rifles\ESP_G36C\data\ESP_G36C.rvmat","Survivalists_RPWeapons\rifles\ESP_G36C\data\ESP_G36C_Body.rvmat"}}
					};
				};
			};
		};
		class SemiAuto: Mode_SemiAuto
		{
			soundSetShot[]=
			{
				"AUG_Shot_SoundSet",
				"AUG_Tail_SoundSet",
				"AUG_InteriorTail_SoundSet"
			};
			soundSetShotExt[]=
			{
				
				{
					"AUG_silencer_SoundSet",
					"AUG_silencerTail_SoundSet",
					"AUG_silencerInteriorTail_SoundSet"
				},
				
				{
					"AUG_silencerHomeMade_SoundSet",
					"AUG_silencerHomeMadeTail_SoundSet",
					"AUG_silencerInteriorHomeMadeTail_SoundSet"
				}
			};
			begin1[]=
			{
				"",
				1,
				1,
				1000
			};
			begin2[]=
			{
				"",
				1,
				1,
				1000
			};
			begin3[]=
			{
				"",
				1,
				1,
				1000
			};
			soundBegin[]=
			{
				"begin1",
				0.33333001,
				"begin2",
				0.33333001,
				"begin3",
				0.33333001
			};
			reloadTime=0.085000001;
			dispersion=0.0015;
			magazineSlot="magazine";
			beginSilenced_Pro[]=
			{
				"",
				1,
				1,
				75
			};
			beginSilenced_HomeMade[]=
			{
				"",
				1,
				1,
				100
			};
			soundBeginExt[]=
			{
				
				{
					"beginSilenced_Pro",
					1
				},
				
				{
					"beginSilenced_HomeMade",
					1
				}
			};
		};
		class FullAuto: Mode_FullAuto
		{
			soundSetShot[]=
			{
				"AUG_Shot_SoundSet",
				"AUG_Tail_SoundSet",
				"AUG_InteriorTail_SoundSet"
			};
			soundSetShotExt[]=
			{
				
				{
					"AUG_silencer_SoundSet",
					"AUG_silencerTail_SoundSet",
					"AUG_silencerInteriorTail_SoundSet"
				},
				
				{
					"AUG_silencerHomeMade_SoundSet",
					"AUG_silencerHomeMadeTail_SoundSet",
					"AUG_silencerInteriorHomeMadeTail_SoundSet"
				}
			};
			begin1[]=
			{
				"",
				1,
				1,
				1000
			};
			begin2[]=
			{
				"",
				1,
				1,
				1000
			};
			begin3[]=
			{
				"",
				1,
				1,
				1000
			};
			soundBegin[]=
			{
				"begin1",
				0.33333001,
				"begin2",
				0.33333001,
				"begin3",
				0.33333001
			};
			beginSilenced_Pro[]=
			{
				"",
				1,
				1,
				75
			};
			beginSilenced_HomeMade[]=
			{
				"",
				1,
				1,
				100
			};
			soundBeginExt[]=
			{
				
				{
					"beginSilenced_Pro",
					1
				},
				
				{
					"beginSilenced_HomeMade",
					1
				}
			};
			reloadTime=0.090000004;
			dispersion=0.0015;
			magazineSlot="magazine";
		};
	};
};