// base kit, chooses the category
class SRP_DecorativeLightKit_Kit extends SRP_IntermediateCraftingKitBase{};
// long light kit, chooses the color
class SRP_DecorativeLight_LongKit_Kit extends SRP_IntermediateCraftingKitBase{};

class SRP_DecorativeLight_Long_Colorbase extends SRP_Container_Base{};
class SRP_DecorativeLight_Long_Blue extends SRP_DecorativeLight_Long_Colorbase{};
class SRP_DecorativeLight_Long_Green extends SRP_DecorativeLight_Long_Colorbase{};
class SRP_DecorativeLight_Long_LightBlue extends SRP_DecorativeLight_Long_Colorbase{};
class SRP_DecorativeLight_Long_Orange extends SRP_DecorativeLight_Long_Colorbase{};
class SRP_DecorativeLight_Long_Pink extends SRP_DecorativeLight_Long_Colorbase{};
class SRP_DecorativeLight_Long_Purple extends SRP_DecorativeLight_Long_Colorbase{};
class SRP_DecorativeLight_Long_Rainbow extends SRP_DecorativeLight_Long_Colorbase{};
class SRP_DecorativeLight_Long_Red extends SRP_DecorativeLight_Long_Colorbase{};
class SRP_DecorativeLight_Long_Yellow extends SRP_DecorativeLight_Long_Colorbase{};
class SRP_DecorativeLight_Long_White extends SRP_DecorativeLight_Long_Colorbase{};

class SRP_DecorativeLight_VerticalLongKit_Kit extends SRP_IntermediateCraftingKitBase{};

class SRP_DecorativeLight_VerticalLong_Colorbase extends SRP_Container_Base{};
class SRP_DecorativeLight_VerticalLong_Blue extends SRP_DecorativeLight_VerticalLong_Colorbase{};
class SRP_DecorativeLight_VerticalLong_Green extends SRP_DecorativeLight_VerticalLong_Colorbase{};
class SRP_DecorativeLight_VerticalLong_LightBlue extends SRP_DecorativeLight_VerticalLong_Colorbase{};
class SRP_DecorativeLight_VerticalLong_Orange extends SRP_DecorativeLight_VerticalLong_Colorbase{};
class SRP_DecorativeLight_VerticalLong_Pink extends SRP_DecorativeLight_VerticalLong_Colorbase{};
class SRP_DecorativeLight_VerticalLong_Purple extends SRP_DecorativeLight_VerticalLong_Colorbase{};
class SRP_DecorativeLight_VerticalLong_Rainbow extends SRP_DecorativeLight_VerticalLong_Colorbase{};
class SRP_DecorativeLight_VerticalLong_Red extends SRP_DecorativeLight_VerticalLong_Colorbase{};
class SRP_DecorativeLight_VerticalLong_Yellow extends SRP_DecorativeLight_VerticalLong_Colorbase{};
class SRP_DecorativeLight_VerticalLong_White extends SRP_DecorativeLight_VerticalLong_Colorbase{};

class SRP_DecorativeLight_FlatKit_Kit extends SRP_IntermediateCraftingKitBase{};

class SRP_DecorativeLight_Flat_Colorbase extends SRP_Container_Base{};
class SRP_DecorativeLight_Flat_Blue extends SRP_DecorativeLight_Flat_Colorbase{};
class SRP_DecorativeLight_Flat_Green extends SRP_DecorativeLight_Flat_Colorbase{};
class SRP_DecorativeLight_Flat_LightBlue extends SRP_DecorativeLight_Flat_Colorbase{};
class SRP_DecorativeLight_Flat_Orange extends SRP_DecorativeLight_Flat_Colorbase{};
class SRP_DecorativeLight_Flat_Pink extends SRP_DecorativeLight_Flat_Colorbase{};
class SRP_DecorativeLight_Flat_Purple extends SRP_DecorativeLight_Flat_Colorbase{};
class SRP_DecorativeLight_Flat_Rainbow extends SRP_DecorativeLight_Flat_Colorbase{};
class SRP_DecorativeLight_Flat_Red extends SRP_DecorativeLight_Flat_Colorbase{};
class SRP_DecorativeLight_Flat_Yellow extends SRP_DecorativeLight_Flat_Colorbase{};
class SRP_DecorativeLight_Flat_White extends SRP_DecorativeLight_Flat_Colorbase{};

class SRP_DecorativeLight_VerticalFlatKit_Kit extends SRP_IntermediateCraftingKitBase{};

class SRP_DecorativeLight_VerticalFlat_Colorbase extends SRP_Container_Base{};
class SRP_DecorativeLight_VerticalFlat_Blue extends SRP_DecorativeLight_VerticalFlat_Colorbase{};
class SRP_DecorativeLight_VerticalFlat_Green extends SRP_DecorativeLight_VerticalFlat_Colorbase{};
class SRP_DecorativeLight_VerticalFlat_LightBlue extends SRP_DecorativeLight_VerticalFlat_Colorbase{};
class SRP_DecorativeLight_VerticalFlat_Orange extends SRP_DecorativeLight_VerticalFlat_Colorbase{};
class SRP_DecorativeLight_VerticalFlat_Pink extends SRP_DecorativeLight_VerticalFlat_Colorbase{};
class SRP_DecorativeLight_VerticalFlat_Purple extends SRP_DecorativeLight_VerticalFlat_Colorbase{};
class SRP_DecorativeLight_VerticalFlat_Rainbow extends SRP_DecorativeLight_VerticalFlat_Colorbase{};
class SRP_DecorativeLight_VerticalFlat_Red extends SRP_DecorativeLight_VerticalFlat_Colorbase{};
class SRP_DecorativeLight_VerticalFlat_Yellow extends SRP_DecorativeLight_VerticalFlat_Colorbase{};
class SRP_DecorativeLight_VerticalFlat_White extends SRP_DecorativeLight_VerticalFlat_Colorbase{};

class SRP_DecorativeLight_LongFancyKit_Kit extends SRP_IntermediateCraftingKitBase{};

class SRP_DecorativeLight_LongFancy_Colorbase extends SRP_Container_Base{};
class SRP_DecorativeLight_LongFancy_Blue extends SRP_DecorativeLight_LongFancy_Colorbase{};
class SRP_DecorativeLight_LongFancy_Green extends SRP_DecorativeLight_LongFancy_Colorbase{};
class SRP_DecorativeLight_LongFancy_LightBlue extends SRP_DecorativeLight_LongFancy_Colorbase{};
class SRP_DecorativeLight_LongFancy_Orange extends SRP_DecorativeLight_LongFancy_Colorbase{};
class SRP_DecorativeLight_LongFancy_Pink extends SRP_DecorativeLight_LongFancy_Colorbase{};
class SRP_DecorativeLight_LongFancy_Purple extends SRP_DecorativeLight_LongFancy_Colorbase{};
class SRP_DecorativeLight_LongFancy_Rainbow extends SRP_DecorativeLight_LongFancy_Colorbase{};
class SRP_DecorativeLight_LongFancy_Red extends SRP_DecorativeLight_LongFancy_Colorbase{};
class SRP_DecorativeLight_LongFancy_Yellow extends SRP_DecorativeLight_LongFancy_Colorbase{};
class SRP_DecorativeLight_LongFancy_White extends SRP_DecorativeLight_LongFancy_Colorbase{};

class SRP_DecorativeLight_VerticalLongFancyKit_Kit extends SRP_IntermediateCraftingKitBase{};

class SRP_DecorativeLight_VerticalLongFancy_Colorbase extends SRP_Container_Base{};
class SRP_DecorativeLight_VerticalLongFancy_Blue extends SRP_DecorativeLight_VerticalLongFancy_Colorbase{};
class SRP_DecorativeLight_VerticalLongFancy_Green extends SRP_DecorativeLight_VerticalLongFancy_Colorbase{};
class SRP_DecorativeLight_VerticalLongFancy_LightBlue extends SRP_DecorativeLight_VerticalLongFancy_Colorbase{};
class SRP_DecorativeLight_VerticalLongFancy_Orange extends SRP_DecorativeLight_VerticalLongFancy_Colorbase{};
class SRP_DecorativeLight_VerticalLongFancy_Pink extends SRP_DecorativeLight_VerticalLongFancy_Colorbase{};
class SRP_DecorativeLight_VerticalLongFancy_Purple extends SRP_DecorativeLight_VerticalLongFancy_Colorbase{};
class SRP_DecorativeLight_VerticalLongFancy_Rainbow extends SRP_DecorativeLight_VerticalLongFancy_Colorbase{};
class SRP_DecorativeLight_VerticalLongFancy_Red extends SRP_DecorativeLight_VerticalLongFancy_Colorbase{};
class SRP_DecorativeLight_VerticalLongFancy_Yellow extends SRP_DecorativeLight_VerticalLongFancy_Colorbase{};
class SRP_DecorativeLight_VerticalLongFancy_White extends SRP_DecorativeLight_VerticalLongFancy_Colorbase{};

class SRP_DecorativeLight_CornerKit_Kit extends SRP_IntermediateCraftingKitBase{};

class SRP_DecorativeLight_Corner_Colorbase extends SRP_Container_Base{};
class SRP_DecorativeLight_Corner_Blue extends SRP_DecorativeLight_Corner_Colorbase{};
class SRP_DecorativeLight_Corner_Green extends SRP_DecorativeLight_Corner_Colorbase{};
class SRP_DecorativeLight_Corner_LightBlue extends SRP_DecorativeLight_Corner_Colorbase{};
class SRP_DecorativeLight_Corner_Orange extends SRP_DecorativeLight_Corner_Colorbase{};
class SRP_DecorativeLight_Corner_Pink extends SRP_DecorativeLight_Corner_Colorbase{};
class SRP_DecorativeLight_Corner_Purple extends SRP_DecorativeLight_Corner_Colorbase{};
class SRP_DecorativeLight_Corner_Rainbow extends SRP_DecorativeLight_Corner_Colorbase{};
class SRP_DecorativeLight_Corner_Red extends SRP_DecorativeLight_Corner_Colorbase{};
class SRP_DecorativeLight_Corner_Yellow extends SRP_DecorativeLight_Corner_Colorbase{};
class SRP_DecorativeLight_Corner_White extends SRP_DecorativeLight_Corner_Colorbase{};

class SRP_DecorativeLight_HorizontalCornerKit_Kit extends SRP_IntermediateCraftingKitBase{};

class SRP_DecorativeLight_HorizontalCorner_Colorbase extends SRP_Container_Base{};
class SRP_DecorativeLight_HorizontalCorner_Blue extends SRP_DecorativeLight_HorizontalCorner_Colorbase{};
class SRP_DecorativeLight_HorizontalCorner_Green extends SRP_DecorativeLight_HorizontalCorner_Colorbase{};
class SRP_DecorativeLight_HorizontalCorner_LightBlue extends SRP_DecorativeLight_HorizontalCorner_Colorbase{};
class SRP_DecorativeLight_HorizontalCorner_Orange extends SRP_DecorativeLight_HorizontalCorner_Colorbase{};
class SRP_DecorativeLight_HorizontalCorner_Pink extends SRP_DecorativeLight_HorizontalCorner_Colorbase{};
class SRP_DecorativeLight_HorizontalCorner_Purple extends SRP_DecorativeLight_HorizontalCorner_Colorbase{};
class SRP_DecorativeLight_HorizontalCorner_Rainbow extends SRP_DecorativeLight_HorizontalCorner_Colorbase{};
class SRP_DecorativeLight_HorizontalCorner_Red extends SRP_DecorativeLight_HorizontalCorner_Colorbase{};
class SRP_DecorativeLight_HorizontalCorner_Yellow extends SRP_DecorativeLight_HorizontalCorner_Colorbase{};
class SRP_DecorativeLight_HorizontalCorner_White extends SRP_DecorativeLight_HorizontalCorner_Colorbase{};