enum SRP_RPC
{
  CHECK_SRP_CONFIG = 275344,
  SRPC_SOUND_BREWING_YIELD = 272164
}
enum SRP_OptionIDsScript
{
  SRP_OPTION_UISTAT_COLORS = 200
	// OPTION_HUD = 100, //starts at 100 to avoid ID conflict with AT_
	// OPTION_CROSSHAIR,
	// OPTION_GAME_MESSAGES,
	// OPTION_ADMIN_MESSAGES,
	// OPTION_PLAYER_MESSAGES,
	// OPTION_QUICKBAR,
	// OPTION_SERVER_INFO,
	// OPTION_BLEEDINGINDICATION,
	// OPTION_CONNECTIVITY_INFO
};